---
swagger: "2.0"
info:
  description: "This document describes mock API for blacklisting IP addresses and\
    \ e-mail addresses"
  version: "1.0.0"
  title: "CSIRT-MU Blocker"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "cech@ics.muni.cz"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/api"
schemes:
- "http"
- "https"
paths:
  /emails:
    get:
      tags:
      - "email"
      summary: "Get all blocked e-mail addresses"
      description: "Lists all blocked email addresses"
      operationId: "list_email"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Email_ListSuccessResponse"
        "500":
          description: "server fail"
          schema:
            $ref: "#/definitions/Error_Response"
      x-swagger-router-controller: "swagger_server.controllers.email_controller"
    post:
      tags:
      - "email"
      summary: "block email"
      operationId: "emails_post"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Email_AddRecord"
      responses:
        "200":
          description: "ok"
      x-swagger-router-controller: "swagger_server.controllers.email_controller"
    put:
      tags:
      - "email"
      summary: "unblock email"
      operationId: "emails_put"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Email_RemoveRecord"
      responses:
        "200":
          description: "ok"
      x-swagger-router-controller: "swagger_server.controllers.email_controller"
  /ip-addresses:
    get:
      tags:
      - "ip"
      summary: "Get all blocked IP addresses"
      description: "Lists all blocked IP addresses"
      operationId: "list_ip"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/IP_ListSuccessResponse"
        "500":
          description: "server fail"
          schema:
            $ref: "#/definitions/Error_Response"
      x-swagger-router-controller: "swagger_server.controllers.ip_controller"
    post:
      tags:
      - "ip"
      summary: "block ip"
      operationId: "ip_addresses_post"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/IP_AddRecord"
      responses:
        "200":
          description: "ok"
      x-swagger-router-controller: "swagger_server.controllers.ip_controller"
    put:
      tags:
      - "ip"
      summary: "unblock ip"
      operationId: "ip_addresses_put"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/IP_RemoveRecord"
      responses:
        "200":
          description: "ok"
      x-swagger-router-controller: "swagger_server.controllers.ip_controller"
definitions:
  Email:
    type: "object"
    properties:
      direction:
        type: "string"
      email:
        type: "string"
        format: "email"
      expires:
        type: "string"
        format: "date-time"
      listed:
        type: "string"
        format: "date-time"
      reason:
        type: "string"
      who:
        type: "string"
    example:
      direction: "from"
      email: "example@example.com"
      expires: "2000-01-23T04:56:07.000+00:00"
      listed: "2000-01-23T04:56:07.000+00:00"
      reason: "Example reason"
      who: "admin"
  IP:
    type: "object"
    properties:
      category:
        type: "string"
      expires:
        type: "string"
        format: "date-time"
      ip:
        type: "string"
        format: "ipv4"
      listed:
        type: "string"
        format: "date-time"
      reason:
        type: "string"
      who:
        type: "string"
    example:
      category: "phishing"
      expires: "2000-01-23T04:56:07.000+00:00"
      ip: "0.0.0.0"
      listed: "2000-01-23T04:56:07.000+00:00"
      reason: "Example reason"
      who: "admin"
  IP_RemoveRecord:
    properties:
      ip:
        type: "string"
        format: "ip"
      reason:
        type: "string"
  IP_AddRecord:
    properties:
      ip:
        type: "string"
        format: "ip"
      length:
        type: "integer"
      reason:
        type: "string"
  Email_RemoveRecord:
    properties:
      email:
        type: "string"
        format: "email"
      reason:
        type: "string"
      who:
        type: "string"
  Email_AddRecord:
    properties:
      email:
        type: "string"
        format: "email"
      length:
        type: "integer"
      reason:
        type: "string"
      who:
        type: "string"
  IP_ListSuccessResponse:
    type: "object"
    properties:
      count:
        type: "integer"
      results:
        type: "array"
        items:
          $ref: "#/definitions/IP"
    example:
      count: 1
      results:
      - category: "phishing"
        expires: "2000-01-23T04:56:07.000+00:00"
        ip: "0.0.0.0"
        listed: "2000-01-23T04:56:07.000+00:00"
        reason: "Example reason"
        who: "admin"
  Email_ListSuccessResponse:
    type: "object"
    properties:
      count:
        type: "integer"
      results:
        type: "array"
        items:
          $ref: "#/definitions/Email"
    example:
      count: 1
      results:
      - direction: "from"
        email: "example@example.com"
        expires: "2000-01-23T04:56:07.000+00:00"
        listed: "2000-01-23T04:56:07.000+00:00"
        reason: "Example reason"
        who: "admin"
  Error_Response:
    type: "object"
    properties:
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
